[package]
name = "build-support"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1"
globwalk = "0.5"
hostname = "0.1"
libc = "0.2"
quote = "0.6"
regex = "1"
syn = "0.15"
serde_json = "1"
